# NB OF FRAMES TO ANALYZE IN THE VIDEO
NB_SNAPSHOTS_VIDEO_ANALYSIS = 4

# FACE DETECTION MODEL AGE GENDER
FACE_DETECTION_MODEL = 'retinaface'
MODEL_MEAN_VALUES = (104.0, 177.0, 123.0)
BLOB_MEAN_VALUES = (78.426, 87.768, 114.895)
BLOB_SIZE = (450, 450)

# SPEECH EXTRACTION
DEFAULT_SUMMARY_TEXT = "No text to summarize"

# TEXT RECOGNITION 
TEXT_DETECTION_CONFIDENCE_THRESHOLD = 0.5

# TEXT RECOGNITION in YOLO
LIST_BRANDS = ['Nescafe', 'Apple', 'Samsung', 'Honor', 'Oppo', 'Huawei', 'Xiaomi']
LIST_PRODUCTS = ['phone', 'laptop', 'tablet', 'watch', 'headphones']